### ISSUE TITLE
Getting java.io.FileNotFoundException on gradle cached files

### ISSUE THREAD

**Issue by androideveloper** [dipien/bye-bye-jetifier#38]
I'm trying to run the plugin, but constantly getting build failures. After removing the failing lib from dependency tree, I get similar issue on another lib. Also tried to clean the gradle cache, didn't help.
```
Execution failed for task ':canISayByeByeJetifier'.
> java.io.FileNotFoundException: /Users/xxx/.gradle/caches/transforms-2/files-2.1/ae7679f69ed21973ab1a3b0e7a6a8d48/gson-2.8.6.jar (Is a directory)
```

Any ideas what can be the issue?

**Comment by maxirosson** [comment]
Hi. I would need more info. Could you please enable the verbose mode?

```
byeByeJetifier {
	verbose = true
}
```

and then attach the output?

Thanks

**Comment by maxirosson** [comment]
Closing this issue, because there is no response.

**Comment by androideveloper** [comment]
Thanks. Not important for us as we disabled Jetifier recently.
