### ISSUE TITLE
Why are android tools being scanned

### ISSUE THREAD

**Issue by pvegh** [dipien/bye-bye-jetifier#63]
Scanning com.android.tools:common:30.1.0
 Absolute path: <home>/.gradle/caches/modules-2/files-2.1/com.android.tools/common/30.1.0/b26b9573400cb8813a414134ce27f4f131872fca/common-30.1.0.jar
 Graphs to this dependency:
 +---com.android.tools.utp:android-device-provider-ddmlib:30.1.0
     +---com.android.tools:common:30.1.0
 +---com.android.tools.utp:android-device-provider-ddmlib:30.1.0

It is unclear from the output why they are failing the build.

**Comment by maxirosson** [comment]
Could you attach the full logs? If possible, with the verbose mode enabled:

```
byeByeJetifier {
	verbose = true
}
```

**Comment by pvegh** [comment]
I don't attach logs because of the project I work on.
I removed this lib from the project also. Turns out it was false positives. I could disable Jetifier anyway.
